### ISSUE TITLE
Corrupted mbtiles file causes segmentation violation and crashes the server

### ISSUE THREAD

**Issue by ka7eh** [consbio/mbtileserver#55]
Here's the traceback of a sample error:

```
time="2018-03-28T20:33:10Z" level=error msg="Unable to create service set: could not open mbtiles file \"/root/tiles/ace_aqua_rept_ntv.mbtiles\": database disk image is malformed" 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7fc8a1]

goroutine 1 [running]:
github.com/consbio/mbtileserver/handlers.(*ServiceSet).Handler(0x0, 0xa29650, 0x1, 0xc4203e8ca0, 0xc42000e1b8)
	/go/src/github.com/consbio/mbtileserver/handlers/handlers.go:409 +0x61
main.serve()
	/go/src/github.com/consbio/mbtileserver/main.go:161 +0x59f
main.glob..func1(0xea67e0, 0xc4203d7cb0, 0x0, 0x1)
	/go/src/github.com/consbio/mbtileserver/main.go:34 +0x20
github.com/consbio/mbtileserver/vendor/github.com/spf13/cobra.(*Command).execute(0xea67e0, 0xc42000c070, 0x1, 0x1, 0xea67e0, 0xc42000c070)
	/go/src/github.com/consbio/mbtileserver/vendor/github.com/spf13/cobra/command.go:651 +0x23d
github.com/consbio/mbtileserver/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xea67e0, 0x40c62c, 0xc420024118, 0x0)
	/go/src/github.com/consbio/mbtileserver/vendor/github.com/spf13/cobra/command.go:726 +0x2d4
github.com/consbio/mbtileserver/vendor/github.com/spf13/cobra.(*Command).Execute(0xea67e0, 0x0, 0xbea71cdb785791df)
	/go/src/github.com/consbio/mbtileserver/vendor/github.com/spf13/cobra/command.go:685 +0x2b
main.main()
	/go/src/github.com/consbio/mbtileserver/main.go:66 +0x2d
```

**Comment by sikmir** [comment]
## Steps to reproduce
```sh
$ docker-compose up -d
$ cp ~/broken/test.mbtiles ./mbtiles/testdata/
$ docker exec -it mbtileserver sh -c "kill -HUP 1"
$ docker-compose logs mbtileserver
...
mbtileserver     | Reloading...
mbtileserver     | 
mbtileserver     | time="2019-11-04T08:05:06Z" level=info msg="Found 3 mbtiles files in ./tilesets"
mbtileserver     | time="2019-11-04T08:05:06Z" level=error msg="Unable to create service set: could not open mbtiles file \"tilesets/test.mbtiles\": sql: no rows in result set"
mbtileserver     | panic: runtime error: invalid memory address or nil pointer dereference
mbtileserver     | [signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x891c1d]
mbtileserver     | 
mbtileserver     | goroutine 1 [running]:
mbtileserver     | github.com/consbio/mbtileserver/handlers.(*ServiceSet).Handler(0x0, 0xade120, 0x1, 0xc000337d18, 0x8)
mbtileserver     | 	/handlers/handlers.go:480 +0x45d
mbtileserver     | main.serve()
mbtileserver     | 	/main.go:244 +0x87c
mbtileserver     | main.glob..func1(0xf12740, 0xc000342660, 0x1, 0x2)
mbtileserver     | 	/main.go:43 +0x4c
mbtileserver     | github.com/spf13/cobra.(*Command).execute(0xf12740, 0xc000020190, 0x2, 0x2, 0xf12740, 0xc000020190)
mbtileserver     | 	/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:766 +0x2ae
mbtileserver     | github.com/spf13/cobra.(*Command).ExecuteC(0xf12740, 0x0, 0x0, 0xf4b4c0)
mbtileserver     | 	/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x2ec
mbtileserver     | github.com/spf13/cobra.(*Command).Execute(...)
mbtileserver     | 	/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800
mbtileserver     | main.main()
mbtileserver     | 	/main.go:145 +0x2e
mbtileserver     | EXITING (abnormal child exit: exit status 2)time="2019-11-04T08:05:13Z" level=info msg="Found 3 mbtiles files in ./tilesets"
mbtileserver     | time="2019-11-04T08:05:13Z" level=error msg="Unable to create service set: could not open mbtiles file \"tilesets/test.mbtiles\": sql: no rows in result set"
mbtileserver     | panic: runtime error: invalid memory address or nil pointer dereference
mbtileserver     | [signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x891c1d]
...
```

**Comment by brendan-ward** [comment]
Yes, I think skipping corrupt mbtiles files with a warning to the user would be reasonable.

Out of curiosity, what caused your mbtiles file to be corrupt in this case?

**Comment by sikmir** [comment]
> Out of curiosity, what caused your mbtiles file to be corrupt in this case?

Well, I can make a PR.

> Out of curiosity, what caused your mbtiles file to be corrupt in this case?

I don't know so far, I've just tried to use tippecanoe for the first time:
```sh
$ tippecanoe -e ./tiles -zg --drop-densest-as-needed ./src/*.geojson
$ mb-util ./tiles test.mbtiles
```
Maybe I'm doing something wrong or something wrong with my data.

**Comment by brendan-ward** [comment]
@sikmir why are you exporting from tippecanoe to a directory?  That might be part of the problem here.  You can export directly to mbtiles:

```
$tippecanoe -o test.mbtiles -zg --drop-densest-as-needed ./src/*.geojson
```

You will need to delete `test.mbtiles` or add the `-f` option (force: delete if exists and create mbtiles file)


Watch for any errors from tippecanoe, usually it is pretty good at alerting you if there was an error creating tiles.

In your above case, your issue is most likely the `*.geojson` expression - you need to reference a specific file rather than a wildcard.

If you have multiple geojson files you are trying to encode into mbtiles at once, you need to do it in a couple steps:
1. create an mbtiles file for each geojson file, using the `-l` option to name the layer in the output
2. use [`tile-join`](https://github.com/mapbox/tippecanoe#tile-join) (part of tippecanoe) to merge the mbtiles files together into a single mbtiles file; each layer in this will have the layer name you specify in the first step.

Example (untested commands):
```
$ tippecanoe -o a.mbtiles -l "A" ./src/a.geojson
$ tippecanoe -o b.mbtiles -l "B" ./src/b.geojson
$ tile-join -o test.mbtiles a.mbtiles b.mbtiles
```

**Comment by sikmir** [comment]
@brendan-ward Thank you for pointing out! I finally managed to get a proper result for my use case after tinkering around with tippecanoe a bit more. That's just a great tool!
